app/views/apps/show.html.erb

We need to use the `clean_name` otherwise we end up with spaces and other weird characters which git/dokky will refuse to work with

Make sure we use the clean name for deploy Url

---

app/models/deploy_key.rb
test/models/deploy_key_test.rb

Dokku does not allow deploy keys that are not parameterized. Since we want to
make sure Dokku gets the proper value, lets parameterize the value in the setter
Fixes: #14

Make sure the deploy key is proparly formatted

---

app/controllers/servers_controller.rb
test/controllers/servers_controller_test.rb
test/integration/new_server_test.rb

We want to give the user a smooth experience, this can be improved by
redirecting to the server object after it has been created. That way the user
gets a better feeling of the Server creation flow.
Fixes #13

Redirect to server after creation

---

app/controllers/application_controller.rb
app/controllers/onboarding_controller.rb
app/views/onboarding/index.html.erb
config/routes.rb
test/controllers/onboarding_controller_test.rb
test/integration/first_launch_test.rb

We don't want administrators messing around on the console to add their first
user, so in order to avoid that I added a welcome page that is shown when there
are no users in the system.
Fixes #20
/cc @michiels / @brambokdam

Show a first launch page when there are no users

---

db/seeds.rb
lib/tasks/seed.rake

When someone installs Intercity, we want to give them access to plugins. Since
we use a database to store them in for now, we also need to seed that DB.
This Rake task will be called upon a intercity-docker bootstrap call (So
everytime someone installs or updates their IC instance), and so it will always
be up to date.
To keep it in sync with dev, and make sure it works correctly, we also use this
task for dev seeding

Seed plugins via a rake task

---

app/jobs/install_server_job.rb
app/views/servers/check_installation.js.erb
app/views/servers/show/add_ssh.html.erb
app/views/servers/show/installing.html.erb
db/migrate/20160112144254_add_install_step_to_server.rb
db/schema.rb

Since the installation can take a little while, it is good to show the user some
feedback on the progress. I did split up the installation in 4 steps:
* Updating packages
* Installing Docker
* Installing Dokku
* Importing base image
We check the output from the server, and determine based on that what the status
should be on the installation page.

Add feedback to the installation process

---

app/views/user_mailer/activation.html.erb

The activation email that you get when you are invited to Intercity looks a bit odd. It suggests that your
email address is your name. Now the email address is removed from the title and the title is just "Welcome to intercity".
Fixes: #54

Remove the email address from the activation mail.

---

Procfile
config/sidekiq.yml

By moving the config here, we can easily add new queues without having to update
the `intercity/intercity-docker` repo.
Fixes: #46

Move sidekiq config to this repository

---

app/models/user.rb
test/controllers/onboarding_controller_test.rb
test/controllers/users_controller_test.rb
test/integration/first_launch_test.rb
test/integration/user_activation_test.rb
test/models/user_test.rb

You could now activate your account with just one char. With this the minimum length of a password is 8 chars.
Fixes: #53

Add password length validation

---

app/assets/javascripts/application.js
app/assets/javascripts/health_check.coffee
app/controllers/health_checks_controller.rb
app/jobs/health_check_job.rb
app/jobs/schedule_health_checks_job.rb
app/views/health_checks/create.js.erb
app/views/servers/show/down.html.erb
config/routes.rb
config/sidekiq_schedule.yml
test/controllers/health_checks_controller_test.rb
test/jobs/health_check_job_test.rb
test/jobs/schedule_health_checks_job_test.rb

The healthchecks should run every 30 minutes to check if the server is still
accessible.
If the server is accessible, we also take the time to sync the Dokku version,
since it might be out of sync if the user manually updated their Dokku instance.
When the server is down, we want to give the user the possibility to force a new
healthcheck, you can do so from the Server is Down page.
Fixes: #28
**Server overview**
**Server is down page**

Add automated healthchecks

---

app/jobs/install_server_job.rb

By setting the proper debconfig variables we can make the installation fully
unattended. So no more Welcome screen anymore!
Fixes #12

Support unattended installation

---

app/controllers/app_services_controller.rb
app/controllers/apps_controller.rb
app/controllers/backups_controller.rb
app/controllers/deploy_keys_controller.rb
app/controllers/domains_controller.rb
app/controllers/env_vars_controller.rb
app/controllers/server_base_controller.rb
app/controllers/servers_controller.rb
app/controllers/services_controller.rb
app/jobs/install_server_job.rb
app/jobs/update_server_job.rb
app/models/server.rb
app/views/servers/_heading.html.erb
app/views/servers/_outdated.html.erb
app/views/servers/manual_update.html.erb
app/views/servers/updating.html.erb
config/application.rb
config/routes.rb
db/migrate/20160108103319_add_updating_to_server.rb
db/schema.rb
lib/version_parser.rb
test/controllers/app_services_controller_test.rb
test/controllers/apps_controller_test.rb
test/fixtures/servers.yml
test/lib/version_parser_test.rb
test/models/server_test.rb

* Show a warning banner if the Dokku version is out of date
* Allow servers with dokku > 0.4.11 to auto update
* Servers with dokku < 0.4.11 need to manually update, show instructions
Fixes: #45

Update servers when newer version is available.

---

app/jobs/schedule_automated_backups_job.rb
test/controllers/backups_controller_test.rb
test/fixtures/apps.yml
test/jobs/schedule_automated_backups_job_test.rb

Currently we backup all the apps. But we only want to run scheduled backups for
apps on which we explicitly enabled it.
Fixes: #73
/cc @michiels / @brambokdam

Only backup apps which backups enabled

---

.rubocop.yml
app/controllers/deploy_keys_controller.rb
app/jobs/create_app_job.rb
app/jobs/create_backup_job.rb
app/jobs/install_server_job.rb
app/jobs/update_server_job.rb
app/models/server.rb

Currently the upgrader got stuck because it asked for the "Main users" SSH key file, which is not
really a requirement. I fixed this by sending a `Enter` (newline) to the server
when we get this question.

Allow for real unattended upgrades

---

app/views/servers/_outdated.html.erb
app/views/servers/manual_update.html.erb

The automatic update is a bit buggy, this will always redirect the update button to the manual update page.

Redirect update button to the manual update page

---

config/application.rb

`autoload_paths` has been removed in rails5, you should now use
`eager_load_paths`

Use eager_load_path instead of autoload_paths

---

config/database.yml

Currently we are running with a pool of just 2, which is giving a lot of
connection issues now that we run the healthchecks.
Increase them to 50 to solve that issue.

Increase the database pool for production

---

app/models/ssh_key_maintainer.rb

In the old version of IC we used the CommandAggregator to check what commands
have been run against a server. Since we are currently not using such a system.
Let's remove this from the codebase

Remove the last pointer to CommandAggregator

---

app/models/ssh_execution.rb
test/jobs/health_check_job_test.rb
test/support/fake_ssh_executioner.rb
test/test_helper.rb

Currently we have to stub out the entire `SshExecution` class, in order not to
actually try to hit a server.
By adding a `FakeSshExecutioner` as a stand-in for the actual lib, we can run
tests without hitting an external server, but still determine the result we want
to get back.
We can improve this later on by also recording what commands have been send to
the `FakeSshExecutioner`.

Add fake SSH Executioner for tests

---

app/assets/javascripts/application.js
app/assets/javascripts/form_errors.coffee
app/views/domains/_form.html.erb
app/views/domains/create.js.erb
app/views/env_vars/_form.html.erb
app/views/env_vars/create.js.erb
app/views/onboarding/index.html.erb
app/views/servers/test_ssh.js.erb
app/views/services/status.js.erb
app/views/users/_form.html.erb
app/views/users/create.js.erb

**Redesign onboarding**
When we moved to Bulma we did forget to style the onboarding page. I added new
styling to that page
**Show errors with fields**
Before the Bulma upgrade, we used bootstrap and bootstrap-form gem. This was
making sure the fields where in red and with the error message near it. Since
we moved to Bulma, we did not show any feedback to the user when there was an
error.
I added styling for that case downside is, it has to be done with a splash of
JS. This is because of the complex'ish html structure for fields with errors in
Bulma
Fixes #118 
**Screenshot/gif**

Redesign onboarding and show errors with fields

---

Gemfile
Gemfile.lock
app/views/users/_user.html.erb
app/views/users/destroy.js.erb
test/integration/manage_users_test.rb
test/test_helper.rb

* Rename the user Destroy action to Remove (Sound more friendly)
* Move from Webkit to Poltergeist
* Add some integration tests for User management
Fixes: #126

Change user Destroy to Remove

---

app/helpers/flash_messages_helper.rb

The flash messages where in a Bootstrap format and broken when we started using Bulma.
Fixes: https://github.com/intercity/intercity-next/issues/133

Flash messages bulma style

---

app/views/services/status.js.erb

In Bulma we use `is-hidden` to hide a element in the JS we used the old bootstrap `hidden` syntax. So the wrong element was added and removed.
Fixes: https://github.com/intercity/intercity-next/issues/127

Service polling broken.

---

app/assets/javascripts/application.js
app/assets/javascripts/modal.coffee
app/controllers/servers_controller.rb
app/models/server.rb
app/views/servers/_empty_state.html.erb
app/views/servers/_new.html.erb
app/views/servers/_server_overview.html.erb
app/views/servers/create.js.erb
app/views/servers/index.html.erb
config/routes.rb
test/controllers/servers_controller_test.rb
test/integration/new_server_test.rb
test/models/server_test.rb
test/test_helper.rb

Currently we move to a new page to create a new server. Since we only have 2
fields, this does not make much sense. We now show a modal to fix this issue.
**Screen**

Create servers via a modal construction

---

CHANGELOG
app/models/server.rb

All new servers will now be installed with Dokku 0.7.0.
Fixes: #158

Update Intercity to Dokku 0.7.0

---

app/assets/javascripts/application.js
app/assets/javascripts/forms.coffee
app/assets/stylesheets/_env-vars.scss
app/assets/stylesheets/_forms.scss
app/assets/stylesheets/application.scss
app/views/env_vars/_env_var.html.erb
app/views/env_vars/index.html.erb

Currently there is a problem where environment variables which are super long
are ruining the layout.
With this fix the env vars are shown in a disabled text field, with a cursor
indicating that it is just read only. When you click the field, it will select
the content within for easy copying.
Fixes: #155
**Screenshot**

Redesign / Improve env var page

---

README.md

We don't need ruby or postgresql (We install that in the docker image), and we
figured out that at least 1024 ram is required.
Fixes: #163

Change requirements

---

doc/installation.md

Since the former installation method was extremly hard to perform (It was a
ridiculous amount of 2 steps!!! :trollface:)
I removed the second step, so the installation can be done by one command.

Make installation easy

---

app/controllers/app_services_controller.rb
app/jobs/link_service_to_app_job.rb
app/models/app.rb
app/models/linked_service.rb
app/views/app_services/_service.html.erb
app/views/app_services/index.html.erb
app/views/app_services/status.js.erb
config/routes.rb
db/migrate/20160830085425_add_status_to_linked_service.rb
db/schema.rb
test/models/app_test.rb

Currently we just redirect the user back to the App overview page, and directly
mark the service as linked. This is not true, since linking a service can take
anywhere between a second up to 30 seconds or more.
In the new situation we show the user that we are linking the service, and poll
to see if the service has been linked.
Fixes: #8

When linking a service to an app, I want to get more feedback

---

CHANGELOG
db/migrate/20160902131047_mark_existing_services_as_linked.rb
db/schema.rb

We did not keep track of the status of a linked service before. Since we do
it now, and the default status is 0, all existing services are marked as
Not Linked. In order to have them show up as linked, we need to update them
all.

Mark existing linked services as Installed

---

CHANGELOG
app/jobs/install_server_job.rb

In some cased downloading buildpacks can take some time (because they download
with 30kb/s). The default timeout is set to 30 seconds. This increases that
timeout to 5 minutes.
Fixes: #11

Ensure we give curl enough time to download buildpacks

---

CHANGELOG
Vagrantfile
app/controllers/servers_controller.rb
app/jobs/create_backup_job.rb
app/jobs/disable_swap_job.rb
app/jobs/enable_ssl_job.rb
app/jobs/enable_swap_job.rb
app/jobs/install_server_job.rb
app/models/server.rb
app/models/ssh_execution.rb
app/views/servers/_new.html.erb
db/migrate/20161123123228_add_user_to_server.rb
db/schema.rb

Sometimes you don't want your server to run as root user, this PR adds a way to
set the user when creating a new server. To make it simple for "normal" usage,
we default to root.
Fixes: #94

Allow server to be installed as other user then root

---

CHANGELOG
config/environments/production.rb

When upgrading to Rails 5 I made a mistake in production.rb. This was
preventing the app to start.

Fix typo in production.rb

---

CHANGELOG
app/jobs/create_deploy_key_job.rb
app/jobs/delete_deploy_key_job.rb
app/jobs/disable_swap_job.rb
app/jobs/enable_swap_job.rb

We currently support running Intercity as another user then `root`. One
issue that comes from this, is that the `intercity` user needs to run some
commands as `sudo` in order for them to be successful.
This adds a fix for thise commands.
Fixes: #224

Run certain commands as sudo

---

CHANGELOG
app/models/server.rb

This PR bumps the Dokku version to 0.12.13.
Things to test:
Note: these were all tested via `root` account (not a sudo user)

Bump standard Dokku version to 0.12.13

---

app/controllers/env_vars_controller.rb
app/jobs/add_env_var_job.rb
app/models/env_var.rb

Make sure to pass apply_immediately into the background job from the controller and don't rely on fetching the setting from the EnvVar model record in the background job.
This because the virtual attribute is not set anymore in the background job when fetching the model record.

Fix bug in passing apply_immediately setting to AddEnvVarJob

---

app/jobs/delete_env_var_job.rb

This PR adds the `-no-restart` option to the Dokku command to remove an env var from an app. This to ensure that when removing multiple ENV vars shortly after each other, we don't get the race condition and dangling container problem as described in #254 and #247

Do not immediately restart when removing an env var

---

app/jobs/disable_ssl_job.rb
app/jobs/enable_ssl_job.rb
test/jobs/disable_ssl_job_test.rb

This PR makes a small fix for #226 so that the SSL certificate adding and removal commands are executed via `sudo`. This fixes this feature for servers where a sudo account is used to manage Intercity and Dokku, instead of a full root account.
Fixes #226

Execute SSL management commands via sudo

---

.circleci/config.yml
Gemfile
Gemfile.lock

This PR adds a simple CirleCI config to `circleci/config.yml` so that we can start building intercity-next on CircleCI. CircleCI also offers a free public plan for public repositories on GitHub.
This sample file is taken from some other Firmhouse projects and uses a basic Postgres, Redis, Ruby, Rails setup.

Add a CircleCI config
