Gemfile, Gemfile.lock, app/assets/stylesheets/_login.scss, app/assets/stylesheets/application.scss, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/layouts/login.html.erb, app/views/sessions/new.html.erb, config/initializers/sorcery.rb, config/routes.rb, db/migrate/20151209133744_sorcery_core.rb, db/schema.rb, db/seeds.rb, test/controllers/app_services_controller_test.rb, test/controllers/apps_controller_test.rb, test/controllers/deploy_keys_controller_test.rb, test/controllers/env_vars_controller_test.rb, test/controllers/servers_controller_test.rb, test/controllers/services_controller_test.rb, test/controllers/sessions_controller_test.rb, test/fixtures/users.yml, test/integration/app_overview_test.rb, test/integration/create_new_app_test.rb, test/integration/new_server_test.rb, test/integration/user_login_test.rb, test/models/user_test.rb, test/test_helper.rb
To make sure we have a secure platform, lets add some authentication.
Fixes: #4
=> Add authentication

app/controllers/apps_controller.rb, app/controllers/domains_controller.rb, app/jobs/add_domain_job.rb, app/jobs/create_app_job.rb, app/jobs/delete_domain_job.rb, app/models/app.rb, app/models/domain.rb, app/views/apps/_app.html.erb, app/views/apps/_heading.html.erb, app/views/apps/new.html.erb, app/views/apps/show.html.erb, app/views/domains/_domain.html.erb, app/views/domains/_form.html.erb, app/views/domains/create.js.erb, app/views/domains/destroy.js.erb, app/views/domains/index.html.erb, config/routes.rb, db/migrate/20151209123528_create_domains.rb, db/migrate/20151209133546_remove_domain_from_app.rb, db/schema.rb, test/controllers/apps_controller_test.rb, test/controllers/domain_controller_test.rb, test/fixtures/domains.yml, test/integration/create_new_app_test.rb, test/models/app_test.rb, test/models/domain_test.rb
=> Added multiple domain support for apps

.sample.env, Gemfile, Gemfile.lock, Procfile, config/database.yml, config/nginx.sample.conf, config/puma.rb
* We are moving to Puma
* Adding a sample nginx config
=> Prepare for Docker based deployment

config/routes.rb, lib/user_constraint.rb
We only want authenticated users to access the sidekiq webinterface
=> Make sure Sidekiq admin is secure

app/assets/stylesheets/_bootswatch.scss, app/assets/stylesheets/_layout.scss, app/assets/stylesheets/_variables.scss, app/assets/stylesheets/application.scss, app/helpers/application_helper.rb, app/helpers/flash_messages_helper.rb, app/views/layouts/application.html.erb, app/views/sessions/new.html.erb
* Added Bootswatch - Sandstone as theme
* Added Gravatar with Identicon fallback
**Login**
**App**
=> Added some basic styling

app/models/app.rb, app/models/server.rb, test/models/app_test.rb, test/models/server_test.rb
=> Fixes foreign key exceptions when removing a server or an app.

app/controllers/services_controller.rb
=> Order services by name

db/schema.rb
Somehow the schema.rb was not generated properly with last changes, still add it
=> Add proper schema.rb

app/views/servers/new.html.erb
=> Remove text that Docker is required on the server

Gemfile, Gemfile.lock, app/models/user.rb, test/models/user_test.rb
With this we now validate for valid user email addresses.
Fixes: #55
=> Validate for valid email address

app/controllers/user_activation_controller.rb, app/controllers/users_controller.rb, app/mailers/user_mailer.rb, app/views/user_activation/edit.html.erb, config/routes.rb, test/controllers/user_activation_controller_test.rb, test/controllers/users_controller_test.rb, test/integration/user_activation_test.rb
The activation actions where stuffed in the UsersController. It looks better if it has it's own
ActivationController.
- Moved the activate and confirm methods from the UsersController to the ActivationController
=> Refactor the activation actions in the UsersController

app/controllers/users_controller.rb, app/views/users/_user.html.erb, app/views/users/index.html.erb, app/views/users/resend_activation_mail.js.erb, config/routes.rb, test/controllers/users_controller_test.rb
It would if a user lost his password to be able to resend his activation email.
- Fixes #51
=> Send users there activation email again

README.md, doc/installation.md
This PR adds the very basic installation instructions. We can improve on the go and when there are questions from people.
=> Added installation instructions for Intercity

app/assets/stylesheets/_services.scss
Currently when you have 2 active services it looks odd (Alignment is off). By
adding a bit more min-height this gets fixed
=> Align the service boxes better

app/assets/javascripts/application.js, app/assets/stylesheets/_layout.scss, app/views/servers/manual_update.html.erb
Copy of: #117
Commited on behalf of @brambokdam in PR #117
=> Design improvement manual update page.

app/assets/stylesheets/_tooltip.scss, app/assets/stylesheets/application.scss, app/views/users/_user.html.erb, app/views/users/index.html.erb
In order to make security more obvious for administrators, we want to show if a
user has 2fa enabled or not.
**Screenshot**
=> Indicate if a user has 2fa enabled or not on user overview

app/assets/stylesheets/_layout.scss, app/views/application/_navigation.html.erb
* Added some shadow
* Added some padding on smaller screens
**Screen**
=> Some styletweaks to the navigation bar

app/assets/stylesheets/_servers.scss, app/views/servers/check_installation.js.erb, app/views/servers/show/installing.html.erb
Fixes: #146 
**Old screen**
**New screen**
=> Redesign server installation screen

app/jobs/rotate_backups_job.rb, app/views/backups/_backup.html.erb, app/views/backups/index.html.erb, config/sidekiq_schedule.yml, db/migrate/20160822140931_add_rotated_to_backup.rb, db/schema.rb
=> Rotate backups that are older then 2 days

app/models/server.rb, test/models/server_test.rb
=> Mark server as outdated in a proper way

CHANGELOG, app/models/server.rb
=> Update Dokku to latest version

.gitignore, app/controllers/servers_controller.rb
Refactor ServersController by using `before_action`
Add .idea to gitignore (for RubyMine IDE)
=> Refactor ServersController

CHANGELOG, app/models/server.rb
We currently are outdated on out Dokku version. This upgrades it to the
latest version.
=> Upgrade to lates Dokku version
